

apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::119178345111:role/terraform-eks-demo-node
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::119178345111:user/user-1
      username: user-1
      groups:
        - eks-role
    - rolearn: arn:aws:iam::119178345111:user/user-2
      username: user-2
      groups:
        - eks-role
